//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flux.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ccy
    {
        public Ccy()
        {
            this.CcyXRates = new HashSet<CcyXRate>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string CCYId { get; set; }
        public string CcyISO { get; set; }
    
        public virtual ICollection<CcyXRate> CcyXRates { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
