//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flux.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment
    {
        public Investment()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int InvestmentId { get; set; }
        public int BusinessUnitId { get; set; }
        public string Name { get; set; }
        public double Amount { get; set; }
        public string Ccy { get; set; }
        public System.DateTime DateFirstDrawdown { get; set; }
        public string Descr { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime DateTimeUpdated { get; set; }
        public string UserUpdated { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
