//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flux.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int InvestmentId { get; set; }
        public string Title { get; set; }
        public decimal LandmarkAmount { get; set; }
        public string CcyId { get; set; }
        public System.DateTime DateTransfer { get; set; }
        public string TimingId { get; set; }
        public string FundVehicleId { get; set; }
        public decimal InvestmentAmount { get; set; }
        public int TransactionTypeId { get; set; }
        public string CertaintyValueId { get; set; }
        public int BoardApproved { get; set; }
        public int FrequencyId { get; set; }
        public string FrequencyDescr { get; set; }
        public Nullable<decimal> ReturnOfCapital { get; set; }
        public int TaxPaid { get; set; }
        public Nullable<decimal> GrossDistribution { get; set; }
        public string Descr { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime DateTimeUpdated { get; set; }
        public string UserUpdated { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public string ActualCcy { get; set; }
        public Nullable<System.DateTime> ActualDateTransfer { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Ccy Ccy { get; set; }
        public virtual Investment Investment { get; set; }
    }
}
